Sprint 2
PaulMosquito/middle.messenger.praktikum.yandex pull request #2
Opened 2022-04-10 20:34 UTC by PaulMosquito

2022-04-11 13:38 UTC, podlovchenko requested changes
Привет, хорошая работа с css константами)
Не могу принять работу, очень много файлов на js, нужно:
1. Переписать js файлы на typescript, добавить описание типов (как можно меньше использовать any и приведение типов через as)
2. Настроить eslint так, чтобы не приходилось пользоваться eslint-disable на весь файл и игнорированием отдельных проверок
3. Разобраться с форматированием кода, лучше выносить шаблоны в отдельный файл
4. Актуализировать ссылку на netlify
5. Добиться прохождения pr чеков

2022-04-11 13:38 UTC, podlovchenko commented on package.json
> +    "@typescript-eslint/eslint-plugin": "^5.17.0",
Лучше задавать фиксированные версии зависимостям, чтобы избежать ошибок из-за разных версий зависимостей  в случае удаления package-lock.json

2022-04-11 13:38 UTC, podlovchenko commented on src/utils/utils.ts
> +	return true;
Можно проверить одним регулярным выражением `/^(?=.*[A-Z])(?=.*\d)[A-Za-z\d]{8,40}$/`

2022-04-11 13:38 UTC, podlovchenko commented on src/pages/page.js
> +/* eslint-disable */
Не стоит злоупотреблять выключением eslint, стоит привести код в порядок в соответствии с выбранными настройками

2022-04-11 22:30 UTC, PaulMosquito commented on src/utils/utils.ts
> +	return true;
fixed

2022-04-11 22:30 UTC, PaulMosquito commented on src/pages/page.js
> +}
fixed

2022-04-11 22:30 UTC, PaulMosquito commented on src/pages/page.js
> +/* eslint-disable */
fixed

2022-04-12 01:03 UTC, PaulMosquito commented on package.json
> +    "@typescript-eslint/eslint-plugin": "^5.17.0",
fixed

2022-04-12 01:04 UTC, PaulMosquito commented
Замечания https://github.com/PaulMosquito/middle.messenger.praktikum.yandex/pull/2#pullrequestreview-937984128 исправлены

2022-04-12 08:13 UTC, podlovchenko requested changes
Привет) Уже лучше
1. Клики на ссылки обрабатываются неправильно
2. Ошибки валидации нужно показать визуально
3. По заданию нужен сбор данных из формы при сабмите формы ( сейчас у тебя выводятся отдельные поля в консоль)
4. Ошибок в консоли не должно быть
<img width="652" alt="Снимок экрана 2022-04-12 в 11 04 57" src="https://user-images.githubusercontent.com/22602747/162912373-1e8d4aae-293e-4197-8fba-6f1ac305be2b.png">

2022-04-12 08:13 UTC, podlovchenko commented on src/core/HTTPTransport.ts
> +        options: { headers: Record<string, string>, timeout: number, data: Record<string, any> },
Стоит вынести определения типа Options

2022-04-12 08:13 UTC, podlovchenko commented on src/core/HTTPTransport.ts
> +        method: string,
Возможные методы лучше задать через enum и указать тип

2022-04-12 08:20 UTC, PaulMosquito commented
@podlovchenko
Привет, а подскажи пожалуйста, что значит сбор данных из формы?
> Клики на ссылки обрабатываются неправильно
Можно ли сейчас упустить этот момент, тк в следующем спринте будет роут делать, а сейчас нужно будет свои велосипеды придумывать. Сейчас так, потому что при билде не видно друг страниц путей кроме /

2022-04-12 08:26 UTC, podlovchenko commented
Например, в форме login по нажатию на кнопку signin в консоли должен быть выведен объект 
```
{
    login: ...,
    password: ...,
}
```

Насчет роутинга окей

2022-04-12 14:18 UTC, PaulMosquito commented on src/core/HTTPTransport.ts
> +        options: { headers: Record<string, string>, timeout: number, data: Record<string, any> },
fixed

2022-04-12 14:18 UTC, PaulMosquito commented
https://github.com/PaulMosquito/middle.messenger.praktikum.yandex/pull/2#pullrequestreview-939107919 - fixed

2022-04-12 14:31 UTC, podlovchenko commented on src/utils/utils.ts
> +export const checkEmail = (str = ''):boolean => !!str.match(/[\w-]@[a-zA-Z]{3}\./);
Вот такое dsads@yexs.rваыавы проходит, а test@gmail.com

2022-04-12 14:31 UTC, podlovchenko approved these changes
Принимаю работу)

2022-04-12 14:34 UTC, PaulMosquito commented on src/utils/utils.ts
> +export const checkEmail = (str = ''):boolean => !!str.match(/[\w-]@[a-zA-Z]{3}\./);
<img width="585" alt="Screenshot 2022-04-12 at 17 34 01" src="https://user-images.githubusercontent.com/31850430/162986764-b9ef3fe0-ce76-43e5-a4bb-c8ffefe7d657.png">
А так в задании написано было

2022-04-12 14:34 UTC, PaulMosquito commented on src/utils/utils.ts
> +export const checkEmail = (str = ''):boolean => !!str.match(/[\w-]@[a-zA-Z]{3}\./);
А латиницу сделаю

2022-04-14 20:28 UTC, merged